default: &default
  adapter: postgresql
  encode: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: MyTeam_development
  #database: de36h603dops8p

test:
  <<: *default
  database: MyTeam_development

production:
  <<: *default
  database: MyTeam_production
