default: &default
  adapter: postgresql
  encode: unicode
  pool: 5
  timeout: 5000
  host: ec2-54-83-59-203.compute-1.amazonaws.com
  username: gzgmfpnetwrtgl
  password: oyCemn3wdcUc2huPq7pvhFNiLJ

development:
  <<: *default
  #database: MyTeam_development
  database: de36h603dops8p

test:
  <<: *default
  database: MyTeam_development

production:
  <<: *default
  database: MyTeam_production
